kind: pipeline
type: docker
name: Build and Publish Image
trigger:
  event:
  - push
  branch:
    include:
    - main

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
          from_secret: DOCKERHUB_PASSWORD
      repo: jackbailey/portfolio
      dockerfile: Dockerfile