name: DEPLOY TO STAGING
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get project files
        uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@master
      - name: Installing project dependencies
        run: yarn
      - name: Building the project
        run: yarn build
      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@master
        with:
          source: "dist"
          storageZoneName: "jackbailey-portfolio"
          accessKey: "${{ secrets.BUNNY_CDN_STORAGE_KEY }}"
      - name: Purge BunnyCDN Cache
        uses: wei/curl@master
        with:
          args: -X POST --url "https://api.bunny.net/purge?url=https%3A%2F%2Fjackbailey.dev%2F%2A" --header "AccessKey:${{ secrets.BUNNY_API_KEY }}"
      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            Project built and deployed to BunnyCDN
            - Production Domain: [jackbailey.dev][1]

            [1]: https://jackbailey.dev
        
