name: Build and Deploy
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get project files
              uses: actions/checkout@master
            - name: Install node
              uses: actions/setup-node@master
            - name: Install yarn
              run: npm install -g yarn
            - name: Installing project dependencies
              run: yarn
            - name: Building the project
              run: yarn build
            - name: Deploy to BunnyCDN
              uses: ayeressian/bunnycdn-storage-deploy@master
              with:
                  source: "dist"
                  storageZoneName: "jackbailey-portfolio"
                  accessKey: "${{ secrets.BUNNY_CDN_STORAGE_KEY }}"
                  purge: true
                  pullZoneId: 839637
                  pullZoneAccessKey: "${{ secrets.BUNNY_PULL_ZONE_KEY }}"
            - name: Create commit comment
              uses: peter-evans/commit-comment@v2
              with:
                  body: |
                      Project built and deployed to BunnyCDN
                      - Production Domain: [jackbailey.dev][1]

                      [1]: https://jackbailey.dev
        
