name: DEPLOY TO STAGING
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get project files
        uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@master
      - name: Installing project dependencies
        run: yarn
      - name: Building the project
        run: yarn build
      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@master
        with:
          source: "dist"
          storageZoneName: "jackbailey-portfolio"
          accessKey: "${{ secrets.BUNNY_CDN_STORAGE_KEY }}"
